[Fluidium]
	# Default: 32
	# Range: 0 ~ 63
	FluidOptimizableDist = 32
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	FluidTickDelayChance = 0.5
	"FluidsAlwaysTick(RegistryName)" = []
	"FluidsAlwaysTick(ModID)" = []
