key.debugLevel=0 #int | default: 0
key.SpawngroupCapacities=MONSTER,2;CREATURE,1;AMBIENT,1;AXOLOTLS,1;UNDERGROUND_WATER_CREATURE,1;WATER_CREATURE,1;WATER_AMBIENT,2 #string | default: MONSTER,80;CREATURE,11;AMBIENT,16;AXOLOTLS,6;UNDERGROUND_WATER_CREATURE,6;WATER_CREATURE,6;WATER_AMBIENT,21

